// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';

export function Login(arg1:string):Promise<auth.AppUser>;

export function Logout():Promise<void>;
