// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppEmote {
    "id": string;
    "name": string;
    "lightSrcSet": string;
    "darkSrcSet": string;

    /**
     * 'global' | 'user' | 'channel' | 'seventv'
     */
    "type": string;
    "zeroWidth": boolean;
    "emoteStack": (AppEmote | null)[] | null;
}

export type AppEmoteMap = { [_ in string]?: AppEmote | null } | null;

export interface AppEmoteSet {
    "Id": string;
    "Provider": string;
    "Emotes": AppEmoteMap;
}

export interface NewEmoteSetEvent {
    "BroadcasterId": string;
    "Id": string;
    "Provider": string;
    "Emotes": AppEmoteMap;
}
