// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetGlobalEmotes(access_token: string): $CancellablePromise<$models.AppEmote[] | null> {
    return $Call.ByID(2348908202, access_token);
}

export function GetUserEmotes(access_token: string): $CancellablePromise<$models.AppEmote[] | null> {
    return $Call.ByID(1550766318, access_token);
}
