// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppEmote {
    "id": string;
    "name": string;
    "lightSrcSet": string;
    "darkSrcSet": string;

    /**
     * 'global' | 'user' | 'channel' | 'seventv'
     */
    "type": string;
    "zeroWidth": boolean;
    "emoteStack": (AppEmote | null)[] | null;
}
