// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativeApi$0 from "../../internal/api/nativeApi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../shared/types/models.js";

export function GetTwitchChannelEmotes(broadcaster_id: string): $CancellablePromise<types$0.AppEmoteSet | null> {
    return $Call.ByID(516261966, broadcaster_id);
}

export function GetTwitchGlobalEmotes(): $CancellablePromise<types$0.AppEmoteSet | null> {
    return $Call.ByID(1629199106);
}

export function GetTwitchUserEmotes(): $CancellablePromise<types$0.AppEmoteSet | null> {
    return $Call.ByID(3242829366);
}

export function RequestTwitchChannelEmotes(broadcasterId: string): $CancellablePromise<void> {
    return $Call.ByID(3965765101, broadcasterId);
}

export function RequestTwitchEmotes(broadcasterId: string): $CancellablePromise<void> {
    return $Call.ByID(3606760464, broadcasterId);
}

export function RequestTwitchGlobalEmotes(): $CancellablePromise<void> {
    return $Call.ByID(3151873303);
}

export function RequestTwitchUserEmotes(): $CancellablePromise<void> {
    return $Call.ByID(552065171);
}

/**
 * TODO: add more params for filters & pagination
 */
export function SearchTwitchStreams(query: string): $CancellablePromise<nativeApi$0.ApiGetStreamsRes | null> {
    return $Call.ByID(785134547, query);
}
