// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../shared/types/models.js";

export function GetChannelEmotes(broadcaster_id: string): $CancellablePromise<types$0.AppEmoteSet | null> {
    return $Call.ByID(1363477587, broadcaster_id);
}

export function GetGlobalEmotes(): $CancellablePromise<types$0.AppEmote[] | null> {
    return $Call.ByID(1706581313);
}

export function GetUserEmotes(): $CancellablePromise<types$0.AppEmote[] | null> {
    return $Call.ByID(1101420057);
}
