// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ApiBadgeSet {
    "set_id": string;
    "versions": ApiBadgeSetVersions[] | null;
}

export interface ApiBadgeSetVersions {
    "id": string;
    "image_url_1x": string;
    "image_url_2x": string;
    "image_url_4x": string;
    "title": string;
    "description": string;
    "click_action"?: string | null;
    "click_url"?: string | null;
}

export interface ApiMessageDropReason {
    "code": string;
    "message": string;
}

export interface ApiPostMessagesData {
    "message_id": string;
    "is_sent": boolean;
    "drop_reason"?: ApiMessageDropReason | null;
}

export interface ApiSubscription {
    "id": string;
    "status": string;
    "type": string;
    "version": string;
    "condition": { [_ in string]?: any } | null;
    "created_at": string;
    "transport": ApiSubscriptionTransport;
    "cost": number;
}

export interface ApiSubscriptionTransport {
    "method": string;
    "callback": string;
    "session_id": string;
}
