// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../shared/types/models.js";

export function GetFFZChannelEmotes(broadcasterId: string): $CancellablePromise<types$0.AppEmoteSet | null> {
    return $Call.ByID(2919320580, broadcasterId);
}

export function GetFFZGlobalEmotes(): $CancellablePromise<types$0.AppEmoteSet | null> {
    return $Call.ByID(1871647300);
}

export function RequestFFZChannelEmotes(broadcasterId: string): $CancellablePromise<void> {
    return $Call.ByID(3323190513, broadcasterId);
}

export function RequestFFZEmotes(broadcasterId: string): $CancellablePromise<void> {
    return $Call.ByID(391441020, broadcasterId);
}

export function RequestFFZGlobalEmotes(): $CancellablePromise<void> {
    return $Call.ByID(2026450867);
}
