// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../shared/types/models.js";

export function GetSevenTVChannelEmotes(broadcasterId: string): $CancellablePromise<types$0.AppEmoteSet | null> {
    return $Call.ByID(3276678143, broadcasterId);
}

export function GetSevenTVGlobalEmotes(): $CancellablePromise<types$0.AppEmoteSet | null> {
    return $Call.ByID(1440221541);
}

export function RequestSevenTVChannelEmotes(broadcasterId: string): $CancellablePromise<void> {
    return $Call.ByID(1531740110, broadcasterId);
}

export function RequestSevenTVEmotes(broadcasterId: string): $CancellablePromise<void> {
    return $Call.ByID(3075503305, broadcasterId);
}

export function RequestSevenTVGlobalEmotes(): $CancellablePromise<void> {
    return $Call.ByID(848393602);
}
