// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../internal/api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Connect(): $CancellablePromise<void> {
    return $Call.ByID(3016163026);
}

export function CreateChatSubscription(channelName: string, globalBadgeSets: api$0.ApiBadgeSet[] | null): $CancellablePromise<$models.ChatroomData | null> {
    return $Call.ByID(2870881603, channelName, globalBadgeSets);
}

export function CreateSubscription(condition: $models.ESSubscriptionCondition, subType: string): $CancellablePromise<string> {
    return $Call.ByID(164469809, condition, subType);
}

export function DeleteAllSubscriptions(): $CancellablePromise<void> {
    return $Call.ByID(705441756);
}

export function DeleteChatSubscriptionFromChannelName(channelName: string): $CancellablePromise<void> {
    return $Call.ByID(4150012008, channelName);
}

export function DeleteChatSubscriptionFromSubId(subId: string): $CancellablePromise<void> {
    return $Call.ByID(1223491543, subId);
}

export function DeleteSubscription(subId: string): $CancellablePromise<void> {
    return $Call.ByID(4164798938, subId);
}

export function GetSubscriptions(): $CancellablePromise<api$0.ApiSubscription[] | null> {
    return $Call.ByID(331411654);
}

export function SendChatMessageFromChannelName(channelName: string, messageContent: string, replyId: string | null): $CancellablePromise<api$0.ApiPostMessagesData | null> {
    return $Call.ByID(933703621, channelName, messageContent, replyId);
}
