// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../internal/api/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Connect(): $CancellablePromise<void> {
    return $Call.ByID(3016163026);
}

export function CreateChatSubscription(accessToken: string, userId: string, channelName: string, globalBadgeSets: api$0.ApiBadgeSet[] | null): $CancellablePromise<$models.ChatroomData | null> {
    return $Call.ByID(2870881603, accessToken, userId, channelName, globalBadgeSets);
}

export function CreateSubscription(accessToken: string, condition: $models.ESSubscriptionCondition, subType: string): $CancellablePromise<string> {
    return $Call.ByID(164469809, accessToken, condition, subType);
}

export function DeleteAllSubscriptions(accessToken: string): $CancellablePromise<void> {
    return $Call.ByID(705441756, accessToken);
}

export function DeleteChatSubscriptionFromChannelName(accessToken: string, channelName: string): $CancellablePromise<void> {
    return $Call.ByID(4150012008, accessToken, channelName);
}

export function DeleteChatSubscriptionFromSubId(accessToken: string, subId: string): $CancellablePromise<void> {
    return $Call.ByID(1223491543, accessToken, subId);
}

export function DeleteSubscription(accessToken: string, subId: string): $CancellablePromise<void> {
    return $Call.ByID(4164798938, accessToken, subId);
}

export function GetSubscriptions(accessToken: string): $CancellablePromise<api$0.ApiSubscription[] | null> {
    return $Call.ByID(331411654, accessToken);
}
