// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as emote$0 from "../emote/models.js";

export interface ChatroomData {
    "subId": string;
    "broadcasterId": string;
    "channelEmotes": { [_ in string]?: emote$0.AppEmote | null } | null;
}

export type ESSubscriptionCondition = { [_ in string]?: string } | null;
