// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChannelBadgeSets(arg1, arg2) {
  return window['go']['services']['BadgeService']['GetChannelBadgeSets'](arg1, arg2);
}

export function GetGlobalBadgeSets(arg1) {
  return window['go']['services']['BadgeService']['GetGlobalBadgeSets'](arg1);
}
