// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChannelBadgeSets(arg1:string,arg2:string):Promise<any>;

export function GetGlobalBadgeSets(arg1:string):Promise<any>;
