// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {services} from '../models';

export function GetAppEmoteFromApiEmote(arg1:api.ApiGlobalEmote,arg2:string):Promise<services.AppEmote>;

export function GetGlobalEmotes(arg1:string):Promise<any>;
