// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppEmoteFromApiEmote(arg1, arg2) {
  return window['go']['services']['EmoteService']['GetAppEmoteFromApiEmote'](arg1, arg2);
}

export function GetGlobalEmotes(arg1) {
  return window['go']['services']['EmoteService']['GetGlobalEmotes'](arg1);
}
