// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGlobalEmotes(arg1) {
  return window['go']['services']['EmoteService']['GetGlobalEmotes'](arg1);
}

export function GetUserEmotes(arg1) {
  return window['go']['services']['EmoteService']['GetUserEmotes'](arg1);
}
