// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['services']['EventSubService']['Connect']();
}

export function CreateSubscription(arg1, arg2, arg3) {
  return window['go']['services']['EventSubService']['CreateSubscription'](arg1, arg2, arg3);
}
