// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function Connect():Promise<void>;

export function CreateSubscription(arg1:services.User,arg2:services.ESSubscriptionCondition,arg3:string):Promise<any>;
