// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['services']['EventSubService']['Connect']();
}

export function CreateSubscription(arg1, arg2, arg3) {
  return window['go']['services']['EventSubService']['CreateSubscription'](arg1, arg2, arg3);
}

export function DeleteAllSubscriptions(arg1) {
  return window['go']['services']['EventSubService']['DeleteAllSubscriptions'](arg1);
}

export function DeleteSubscription(arg1, arg2) {
  return window['go']['services']['EventSubService']['DeleteSubscription'](arg1, arg2);
}

export function GetSubscriptions(arg1) {
  return window['go']['services']['EventSubService']['GetSubscriptions'](arg1);
}
