// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGlobalEmotes(arg1:string):Promise<any>;

export function GetUserEmotes(arg1:string):Promise<any>;
