// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../shared/types/models.js";

export function GetBTTVChannelEmotes(broadcasterId: string): $CancellablePromise<types$0.AppEmoteSet | null> {
    return $Call.ByID(292433402, broadcasterId);
}

export function GetBTTVGlobalEmotes(): $CancellablePromise<types$0.AppEmoteSet | null> {
    return $Call.ByID(2796899158);
}

export function RequestBTTVChannelEmotes(broadcasterId: string): $CancellablePromise<void> {
    return $Call.ByID(4220323541, broadcasterId);
}

export function RequestBTTVEmotes(broadcasterId: string): $CancellablePromise<void> {
    return $Call.ByID(412032584, broadcasterId);
}

export function RequestBTTVGlobalEmotes(): $CancellablePromise<void> {
    return $Call.ByID(4018971775);
}
