// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['eventsub']['EventSubService']['Connect']();
}

export function CreateChatSubscription(arg1, arg2, arg3, arg4) {
  return window['go']['eventsub']['EventSubService']['CreateChatSubscription'](arg1, arg2, arg3, arg4);
}

export function CreateSubscription(arg1, arg2, arg3) {
  return window['go']['eventsub']['EventSubService']['CreateSubscription'](arg1, arg2, arg3);
}

export function DeleteAllSubscriptions(arg1) {
  return window['go']['eventsub']['EventSubService']['DeleteAllSubscriptions'](arg1);
}

export function DeleteChatSubscriptionFromChannelName(arg1, arg2) {
  return window['go']['eventsub']['EventSubService']['DeleteChatSubscriptionFromChannelName'](arg1, arg2);
}

export function DeleteChatSubscriptionFromSubId(arg1, arg2) {
  return window['go']['eventsub']['EventSubService']['DeleteChatSubscriptionFromSubId'](arg1, arg2);
}

export function DeleteSubscription(arg1, arg2) {
  return window['go']['eventsub']['EventSubService']['DeleteSubscription'](arg1, arg2);
}

export function GetSubscriptions(arg1) {
  return window['go']['eventsub']['EventSubService']['GetSubscriptions'](arg1);
}
