// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToChatroom(arg1) {
  return window['go']['main']['App']['ConnectToChatroom'](arg1);
}

export function EnableSevenTV(arg1) {
  return window['go']['main']['App']['EnableSevenTV'](arg1);
}

export function SendChatMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2, arg3);
}
