// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {api} from '../models';

export function ConnectToChatroom(arg1:string):Promise<main.ChatroomData>;

export function SendChatMessage(arg1:string,arg2:string,arg3:any):Promise<api.ApiPostMessagesData>;
