// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {eventsub} from '../models';
import {emote} from '../models';
import {api} from '../models';

export function ConnectToChatroom(arg1:string):Promise<eventsub.ChatroomData>;

export function DisconnectFromChatroom(arg1:string):Promise<void>;

export function EnableSevenTV(arg1:string):Promise<Record<string, emote.AppEmote>>;

export function SendChatMessage(arg1:string,arg2:string,arg3:any):Promise<api.ApiPostMessagesData>;
