// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Login(accessToken: string): $CancellablePromise<$models.AppUser | null> {
    return $Call.ByID(1457994249, accessToken);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(3208692234);
}
