// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export interface AppUser {
    "id": string;
    "login": string;
    "display_name": string;
    "type": string;
    "broadcaster_type": string;
    "description": string;
    "profile_image_url": string;
    "offline_image_url": string;
    "view_count": number;
    "email": string;
    "created_at": time$0.Time;
    "access_token": string;
}
