// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativeApi$0 from "./internal/api/nativeApi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as eventsub$0 from "./services/eventsub/models.js";

export function ConnectToChatroom(channelName: string): $CancellablePromise<eventsub$0.ChatroomData | null> {
    return $Call.ByID(3727907864, channelName);
}

export function DisconnectFromChatroom(channelName: string): $CancellablePromise<void> {
    return $Call.ByID(3340004225, channelName);
}

export function SendChatMessage(channelName: string, messageContent: string, replyId: string | null): $CancellablePromise<nativeApi$0.ApiPostMessagesData | null> {
    return $Call.ByID(2462501357, channelName, messageContent, replyId);
}
